#!/bin/bash

## parse_BUSCO_short_summary - Print the BUSCO results in the "short" summary file in a nicer way.
#
# Example short summary file:

# BUSCO version is: 5.0.0 
# The lineage dataset is: metazoa_odb10 (Creation date: 2021-02-17, number of species: 65, number of BUSCOs: 954)
# Summarized benchmarking in BUSCO notation for file /scratch/timothy/busco/genome.fa
# BUSCO was run in mode: genome
# Gene predictor used: metaeuk
#
#	***** Results: *****
#
# 	C:95.7%[S:94.1%,D:1.6%],F:2.2%,M:2.1%,n:954	   - Line 1
#	913	Complete BUSCOs (C)			   - Line 2
#	898	Complete and single-copy BUSCOs (S)	   - Line 3
#	15	Complete and duplicated BUSCOs (D)	   - Line 4
#	21	Fragmented BUSCOs (F)			   - Line 5
#	20	Missing BUSCOs (M)			   - Line 6
#	954	Total BUSCO groups searched		   - Line 7

VERSION=0.1

F=$@
cat "${F}" \
 | awk '$0!~"#" && $0!="" && $0!~"Results"' \
 | awk '{
	if(NR==1){
		split($1,a,"%");
	}; 
	if(NR==2){
		split(a[1],b,":"); 
		print "Complete\t"$1"\t"b[2]"%";
	};
	if(NR==3){
		split(a[2],b,":");
		print "Single-copy\t"$1"\t"b[2]"%";
	};
	if(NR==4){
		split(a[3],b,":");
		print "Duplicated\t"$1"\t"b[2]"%";
	};
	if(NR==5){
		split(a[4],b,":");
		print "Fragmented\t"$1"\t"b[2]"%";
	};
	if(NR==6){
		split(a[5],b,":");
		print "Missing\t"$1"\t"b[2]"%";
	};
	if(NR==7){
		split(a[6],b,":");
		print "Total\t"$1"\t100%";
	};
   }'

